# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('hora_ini', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('ayudantes', models.BooleanField()),
                ('latitud', models.FloatField(default=0)),
                ('longitud', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('comentario', models.CharField(max_length=1000)),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodFinder.Comedor')),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comedor', models.CharField(max_length=30)),
                ('fecha_den', models.DateField()),
                ('denuncia', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('logo', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('imagen', models.CharField(max_length=500)),
                ('valoracion', models.IntegerField()),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodFinder.Comedor')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=30)),
                ('descp', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsu', models.CharField(default='carlitos', max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(default='suarez', max_length=30)),
                ('correo', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('tipo', models.CharField(default='cliente', max_length=15)),
                ('rol', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Docente', 'Docente'), ('Trabajador', 'Trabajador')], default='Estudiante', max_length=10)),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodFinder.Comedor')),
                ('facultad', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='FoodFinder.Facultad')),
            ],
        ),
        migrations.AddField(
            model_name='comedor',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodFinder.Facultad'),
        ),
    ]
