# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFinder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comedor',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='comedor',
            name='latitud',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comedor',
            name='longitud',
            field=models.FloatField(default=0),
        ),
    ]
