# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFinder', '0002_auto_20170802_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(default='cliente', max_length=30),
        ),
    ]
