# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFinder', '0002_auto_20170802_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_den', models.DateField()),
                ('denuncia', models.CharField(max_length=1000)),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodFinder.Comedor')),
            ],
        ),
    ]
