# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFinder', '0003_comentario_aceptado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
    ]
