# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFinder', '0003_auto_20170812_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='imagen',
            field=models.CharField(max_length=500),
        ),
    ]
