# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFinder', '0004_auto_20170811_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comedor',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='platillo',
            name='distancia',
        ),
        migrations.RemoveField(
            model_name='platillo',
            name='valorNutricional',
        ),
    ]
