# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFinder', '0005_auto_20170903_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='imgPlatillo',
            field=models.ImageField(blank=True, upload_to='fotos'),
        ),
    ]
