# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFinder', '0005_auto_20170811_1605'),
        ('FoodFinder', '0004_auto_20170811_0919'),
    ]

    operations = [
    ]
