# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFinder', '0006_merge_20170811_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='comedor',
            field=models.CharField(max_length=30),
        ),
    ]
