# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFinder', '0006_platillo_imgplatillo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
