# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFinder', '0007_usuario_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='online',
        ),
    ]
